/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.util.ArrayList;
import about.personal;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;
/**
 *
 * @author Mahadi Hassan
 */
public class frm extends javax.swing.JFrame {

    /**
     * Creates new form frm
     */
    

     
    ArrayList<String> nam = new ArrayList<String>();
    ArrayList<Integer> sal = new ArrayList<Integer>();
    ArrayList<String> dep = new ArrayList<String>();   

    cls cls=new cls();
    byte index;
    
    
    
    
    public void read (){
        try {
            nam=cls.read1();
            sal=cls.read2();
            dep=cls.read3();
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("DataBase POP Successfull!");
    }
    
    public void write(){
        cls.write(nam, sal, dep);
        System.out.println("DataBase PUSH Successfull!");
    }
    
    public void update(){
        write();
        read();
        combo();
        System.out.println("DataBase UPDATE Successfull!");
    }
    
    public void delete(){
        nam.remove(n.getSelectedIndex());
        sal.remove(n.getSelectedIndex());
        dep.remove(n.getSelectedIndex());
    }
    
    public void combo(){
        String[] cs=new String[nam.size()];
        for (int i = 0; i < nam.size(); i++) {
            cs[i]=i+1+". "+nam.get(i);
        }
        
        n.setModel(new javax.swing.DefaultComboBoxModel<>(cs));
        System.out.println("List UPDATE Successfull!");
    }
    
        
    public frm() {
        
        initComponents();      
        
        this.setLocationRelativeTo(this);
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("note.png")));
        
        try {
            FileInputStream f=new FileInputStream("crud.dat");
            read();
        } catch (Exception e) {
            write();
            JOptionPane.showMessageDialog(jPanel1, "File Not Found!\nFile Created.", "Alert",JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
            
        }
        combo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        n = new javax.swing.JComboBox<>();
        s = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD - Develop By Mahadi Hassan");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID No.");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dep.");

        n.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nMouseClicked(evt);
            }
        });
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        s.setEditable(false);
        s.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        s.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        d.setEditable(false);
        d.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        d.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jToggleButton1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jToggleButton1.setText("Create");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButton2.setText("Read");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jToggleButton2.setText("Update");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(n, 0, 200, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton2)
                    .addComponent(jToggleButton2)
                    .addComponent(jButton4))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMouseClicked
        // TODO add your handling code here:
        //System.out.println("ii");
    }//GEN-LAST:event_nMouseClicked

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
        if(!jToggleButton1.isSelected() && !jToggleButton2.isSelected()){
            s.setText("- -");
            d.setText("- -");
            System.out.println("Index Selected!");
        }
        
    }//GEN-LAST:event_nActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(nam.size()>0){
            s.setText(sal.get(n.getSelectedIndex()).toString());
            d.setText(dep.get(n.getSelectedIndex()));
            
            System.out.println(n.getSelectedItem());
            System.out.println(n.getSize());
            
            System.out.println(nam);
            System.out.println(sal);
            System.out.println(dep);
        }
        else{
            JOptionPane.showMessageDialog(jPanel1, "List is Empty.", "Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        
        if(jToggleButton1.isSelected()){
            
            jButton2.setEnabled(false);
            jToggleButton2.setEnabled(false);
            jButton4.setEnabled(false);
            
            jToggleButton1.setText("Add");
            n.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
            
            s.setText("");
            d.setText("");
            
            n.setEditable(true);
            s.setEditable(true);
            d.setEditable(true);
        }
        else{
            
            if(s.getText().isEmpty() || d.getText().isEmpty()){
                JOptionPane.showMessageDialog(jPanel1, "Field is Empty!","Alert",JOptionPane.WARNING_MESSAGE);
                jToggleButton1.setSelected(true);
            }
            
            else{
                try {
                    System.out.println((int)Integer.parseInt(s.getText()));
                    
                    jToggleButton1.setText("Create");

                    jButton2.setEnabled(true);
                    jToggleButton2.setEnabled(true);
                    jButton4.setEnabled(true);


                    n.setEditable(false);
                    s.setEditable(false);
                    d.setEditable(false);

                    nam.add(n.getSelectedItem().toString());
                    sal.add(Integer.parseInt(s.getText().trim()));
                    dep.add(d.getText());


                    s.setText("");
                    d.setText("");

                    update();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(jPanel1, "ID Must be Contain a Number!","Error",JOptionPane.ERROR_MESSAGE);
                    jToggleButton1.setSelected(true);
                }
                        
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if(nam.size()>0){
            if(jToggleButton2.isSelected()){
                
                jToggleButton2.setText("Set");
                
                jButton2.doClick();
                
                index=(byte) n.getSelectedIndex();
                n.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{nam.get(index)}));
                
                jButton2.setEnabled(false);
                jToggleButton1.setEnabled(false);
                jButton4.setEnabled(false);
                
                n.setEditable(true);
                s.setEditable(true);
                d.setEditable(true);
                
            }
            else{
                
                if(s.getText().isEmpty() || d.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jPanel1, "Field is Empty!","Alert",JOptionPane.WARNING_MESSAGE);
                    jToggleButton2.setSelected(true);
                }
                
                else{
                    try {
                        System.out.println((int)Integer.parseInt(s.getText()));
                        
                        jToggleButton2.setText("Update");
                        
                        nam.set(index, n.getSelectedItem().toString());
                        sal.set(index, Integer.parseInt(s.getText().trim()));
                        dep.set(index, d.getText());
                        
                        jButton2.setEnabled(true);
                        jToggleButton1.setEnabled(true);
                        jButton4.setEnabled(true);
                        
                        n.setEditable(false);
                        s.setEditable(false);
                        d.setEditable(false);
                        
                        update();
                        s.setText("");
                        d.setText("");
                        
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(jPanel1, "ID Must be Contain a Number!","Error",JOptionPane.ERROR_MESSAGE);
                        jToggleButton2.setSelected(true);
                    }
                }
                
                
            }                   
        }
        else{
            JOptionPane.showMessageDialog(jPanel1, "List is Empty.", "Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(nam.size()>0){
            s.setText("");
            d.setText("");
            delete();
            update();       
        }
        else{
            JOptionPane.showMessageDialog(jPanel1, "List is Empty.", "Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JComboBox<String> n;
    private javax.swing.JTextField s;
    // End of variables declaration//GEN-END:variables
}
